package by.epam.filmstore.controller;

/**
 * Created by Olga Shahray on 23.07.2016.
 */
public enum CommandName {

    LOAD_MAIN_PAGE,
    USER_AUTHORIZATION,
    CHECK_EMAIL,
    SAVE_NEW_USER,
    GET_FILM_BY_ID,
    GET_FILTERED_FILMS,
    SEARCH_FILM,
    LOGOUT,
    GET_USER,
    USER_UPDATE_PROFILE,
    USER_CHANGE_PASSWORD,
    USER_SHOW_UPDATE_PAGE_PROFILE,
    USER_PERSONAL_INFO,
    USER_ADD_COMMENT,
    USER_GET_ORDERS,
    USER_GET_COMMENTS,
    USER_GET_FAVORITE_FILMS,
    USER_ADD_FAVORITE_FILM,
    USER_DELETE_FAVORITE_FILM,
    USER_GET_DISCOUNT,
    USER_CART,
    USER_ADD_TO_CART,
    USER_DELETE_ORDER,
    USER_PAY_ORDER,
    USER_WATCH_FILM,
    ADMIN_GET_USERS,
    ADMIN_GET_FILMS,
    ADMIN_GET_GENRES,
    ADMIN_GET_COUNTRIES,
    ADMIN_GET_DISCOUNTS,
    ADMIN_GET_FILM_MAKERS,
    ADMIN_GET_COMMENTS,
    ADMIN_DELETE_USER,
    ADMIN_DELETE_FILM,
    ADMIN_DELETE_GENRE,
    ADMIN_DELETE_COUNTRY,
    ADMIN_DELETE_DISCOUNT,
    ADMIN_DELETE_FILM_MAKER,
    ADMIN_DELETE_COMMENT,
    ADMIN_SAVE_FILM,
    ADMIN_SAVE_GENRE,
    ADMIN_SAVE_COUNTRY,
    ADMIN_SAVE_DISCOUNT,
    ADMIN_SAVE_FILM_MAKER,
    ADMIN_UPDATE_USER,
    ADMIN_UPDATE_COMMENT,
    ADMIN_ADD_PAGE_FILM


}
