package by.epam.filmstore.controller;

/**
 * Created by Olga Shahray on 23.07.2016.
 */
public enum CommandName {

    USER_AUTHORIZATION,
    GET_FILMS_BY_YEAR,
    LOAD_MAIN_PAGE,
    GET_FILM_BY_ID,
    SAVE_NEW_USER,
    LOGOUT,
    GET_USER,
    USER_ADD_COMMENT,
    USER_GET_ORDERS,
    USER_GET_COMMENTS,
    USER_GET_FAVORITE_GENRES,
    USER_SAVE_FAVORITE_GENRES,
    USER_GET_DISCOUNT,
    USER_CART,
    USER_ADD_TO_CART,
    USER_DELETE_ORDER,
    USER_PAY_ORDER,
    ADMIN_GET_USERS,
    ADMIN_GET_FILMS,
    ADMIN_GET_GENRES,
    ADMIN_GET_COUNTRIES,
    ADMIN_GET_DISCOUNTS,
    ADMIN_GET_FILM_MAKERS,
    ADMIN_GET_COMMENTS,
    ADMIN_DELETE_USER,
    ADMIN_DELETE_FILM,
    ADMIN_DELETE_GENRE,
    ADMIN_DELETE_COUNTRY,
    ADMIN_DELETE_DISCOUNT,
    ADMIN_DELETE_FILM_MAKER,
    ADMIN_DELETE_COMMENT,
    ADMIN_SAVE_FILM,
    ADMIN_SAVE_GENRE,
    ADMIN_SAVE_COUNTRY,
    ADMIN_SAVE_DISCOUNT,
    ADMIN_SAVE_FILM_MAKER,
    ADMIN_UPDATE_USER,
    ADMIN_UPDATE_COMMENT,
    ADMIN_ADD_PAGE_FILM


}
