package by.epam.filmstore.controller;

/**
 * Created by Olga Shahray on 23.07.2016.
 */
public enum CommandName {

    USER_AUTHORIZATION,
    CHANGE_LANGUAGE,
    GET_FILMS_BY_YEAR,
    LOAD_MAIN_PAGE,
    GET_FILM_BY_ID,
    SAVE_NEW_USER,
    LOGOUT,
    GET_USER,
    GET_ORDERS_OF_USER,
    GET_COMMENTS_OF_USER,
    GET_FAVORITE_GENRES,
    SAVE_FAVORITE_GENRES,
    SAVE_NEW_FILM,
    GET_DISCOUNT,
    ADMIN_GET_USERS,
    ADMIN_GET_FILMS,
    ADMIN_GET_GENRES,
    ADMIN_GET_COUNTRIES,
    ADMIN_GET_DISCOUNTS,
    ADMIN_GET_FILM_MAKERS,
    ADMIN_GET_COMMENTS,
    ADMIN_DELETE_USER,
    ADMIN_DELETE_FILM,
    ADMIN_DELETE_GENRE,
    ADMIN_DELETE_COUNTRY,
    ADMIN_DELETE_DISCOUNT,
    ADMIN_DELETE_FILM_MAKER,
    ADMIN_DELETE_COMMENT


}
